name: Build
on:
  push

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    # https://github.com/3F/DllExport/issues/29#issuecomment-284259126
    - name: Install MS Build Tools 2015
      run: curl https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe -o BuildTools_Full.exe && BuildTools_Full.exe /Q /Full
      shell: cmd
    - name: Prepare Build
      run: nuget restore -OutputDirectory .\Packages EasyHook.sln
    - name: Build x86
      run: msbuild -m EasyHook.sln /p:Configuration=netfx4-Debug /p:Platform=Win32 /p:TargetFrameworkVersion=v4.8 /p:TargetFrameworkProfile=""
    - name: Build x64
      run: msbuild -m EasyHook.sln /p:Configuration=netfx4-Debug /p:Platform=x64 /p:TargetFrameworkVersion=v4.8 /p:TargetFrameworkProfile=""
    - name: Build NuGet Package
      run: nuget pack EasyHook.nuspec -PackagesDirectory packages -Prop Configuration=Release
    - name: Upload x86 Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: x86
        path: |
          Build/netfx4-Debug/x86/*.dll
          Build/netfx4-Debug/x86/*.pdb
          Build/netfx4-Debug/x86/*.XML
          
    - name: Upload x64 Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: x64
        path: |
          Build/netfx4-Debug/x64/*.dll
          Build/netfx4-Debug/x64/*.pdb

    - name: Upload x64 Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NuGet Package
        path: |
          Andraste.EasyHook.*.nupkg
